export const ALL_EXCHANGE_BOOK_REQUEST = "ALL_EXCHANGE_BOOK_EXCHANGE";
export const ALL_EXCHANGE_BOOK_SUCCESS = "ALL_EXCHANGE_BOOK_SUCCESS";
export const ALL_EXCHANGE_BOOK_FAIL = "ALL_EXCHANGE_BOOK_FAIL";

export const NEW_EXCHANGE_BOOK_REQUEST = "NEW_EXCHANGE_BOOK_EXCHANGE";
export const NEW_EXCHANGE_BOOK_SUCCESS = "NEW_EXCHANGE_BOOK_SUCCESS";
export const NEW_EXCHANGE_BOOK_FAIL = "NEW_EXCHANGE_BOOK_FAIL";
export const NEW_EXCHANGE_BOOK_RESET = "NEW_EXCHANGE_BOOK_RESET";

export const NEW_EXCHANGE_DETAILS_REQUEST = "NEW_EXCHANGE_DETAILS_REQUEST";
export const NEW_EXCHANGE_DETAILS_SUCCESS = "NEW_EXCHANGE_DETAILS_SUCCESS";
export const NEW_EXCHANGE_DETAILS_FAIL = "NEW_EXCHANGE_DETAILS_FAIL";


export const ADMIN_EXCHANGE_BOOK_REQUEST = "ADMIN_EXCHANGE_BOOK_REQUEST";
export const ADMIN_EXCHANGE_BOOK_SUCCESS = "ADMIN_EXCHANGE_BOOK_SUCCESS";
export const ADMIN_EXCHANGE_BOOK_FAIL = "ADMIN_EXCHANGE_BOOK_FAIL";

export const UPDATE_EXCHANGE_BOOK_REQUEST = "UPDATE_EXCHANGE_BOOK_REQUEST";
export const UPDATE_EXCHANGE_BOOK_SUCCESS = "UPDATE_EXCHANGE_BOOK_SUCCESS";
export const UPDATE_EXCHANGE_BOOK_RESET = "UPDATE_EXCHANGE_BOOK_RESET";
export const UPDATE_EXCHANGE_BOOK_FAIL = "UPDATE_EXCHANGE_BOOK_FAIL";

export const DELETE_EXCHANGE_BOOK_REQUEST = "DELETE_EXCHANGE_BOOK_REQUEST";
export const DELETE_EXCHANGE_BOOK_SUCCESS = "DELETE_EXCHANGE_BOOK_SUCCESS";
export const DELETE_EXCHANGE_BOOK_RESET = "DELETE_EXCHANGE_BOOK_RESET";
export const DELETE_EXCHANGE_BOOK_FAIL = "DELETE_EXCHANGE_BOOK_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";