export const ALL_SELL_BOOK_REQUEST = "ALL_SELL_BOOK_REQUEST";
export const ALL_SELL_BOOK_SUCCESS = "ALL_SELL_BOOK_SUCCESS";
export const ALL_SELL_BOOK_FAIL = "ALL_SELL_BOOK_FAIL";

export const NEW_SELL_BOOK_REQUEST = "NEW_SELL_BOOK_REQUEST";
export const NEW_SELL_BOOK_SUCCESS = "NEW_SELL_BOOK_SUCCESS";
export const NEW_SELL_BOOK_FAIL = "NEW_SELL_BOOK_FAIL";
export const NEW_SELL_BOOK_RESET = "NEW_SELL_BOOK_RESET"; 

export const NEW_SELL_DETAILS_REQUEST = "NEW_SELL_DETAILS_REQUEST";
export const NEW_SELL_DETAILS_SUCCESS = "NEW_SELL_DETAILS_SUCCESS";
export const NEW_SELL_DETAILS_FAIL = "NEW_SELL_DETAILS_FAIL";


export const ADMIN_SELL_BOOK_REQUEST = "ADMIN_SELL_BOOK_REQUEST";
export const ADMIN_SELL_BOOK_SUCCESS = "ADMIN_SELL_BOOK_SUCCESS";
export const ADMIN_SELL_BOOK_FAIL = "ADMIN_SELL_BOOK_FAIL";

export const UPDATE_SELL_BOOK_REQUEST = "UPDATE_SELL_BOOK_REQUEST";
export const UPDATE_SELL_BOOK_SUCCESS = "UPDATE_SELL_BOOK_SUCCESS";
export const UPDATE_SELL_BOOK_RESET = "UPDATE_SELL_BOOK_RESET";
export const UPDATE_SELL_BOOK_FAIL = "UPDATE_SELL_BOOK_FAIL";

export const DELETE_SELL_BOOK_REQUEST = "DELETE_SELL_BOOK_REQUEST";
export const DELETE_SELL_BOOK_SUCCESS = "DELETE_SELL_BOOK_SUCCESS";
export const DELETE_SELL_BOOK_RESET = "DELETE_SELL_BOOK_RESET";
export const DELETE_SELL_BOOK_FAIL = "DELETE_SELL_BOOK_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";